### ISSUE TITLE
Plugin throws an error on the checkout page on WooCommerce v4.7.1

### ISSUE THREAD

**Issue by abishekrsrikaanth** [razorpay/razorpay-woocommerce-subscriptions#30]
I get the following error when I activate this plugin on my WooCommerce website. Can you please look into it

```
Fatal error: Uncaught Error: Class 'WC_Subscriptions_Cart' not found in /home/forge/www.mywebsite.in/public/wp-content/plugins/razorpay-subscriptions-for-woocommerce/razorpay-subscriptions.php:133 Stack trace: #0 /home/forge/www.mywebsite.in/public/wp-includes/class-wp-hook.php(287): WC_Razorpay_Subscription->disable_non_subscription() #1 /home/forge/www.mywebsite.in/public/wp-includes/plugin.php(206): WP_Hook->apply_filters() #2 /home/forge/www.mywebsite.in/public/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(160): apply_filters() #3 /home/forge/www.mywebsite.in/public/wp-content/plugins/woocommerce/includes/wc-template-functions.php(3739): WC_Payment_Gateways->get_available_payment_gateways() #4 /home/forge/www.mywebsite.in/public/wp-includes/class-wp-hook.php(287): wc_get_pay_buttons() #5 /home/forge/www.mywebsite.in/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters() #6 /home/forge/www.mywebsite.in/public/wp-includes/plugin.php(478): WP_Hook->do_action() #7 /home/forge/www.mywebsite.in/p in /home/forge/www.mywebsite.in/public/wp-content/plugins/razorpay-subscriptions-for-woocommerce/razorpay-subscriptions.php on line 133
```
Can you please advice what may be wrong

**Comment by kudaleganesh** [comment]
I have created the PR for the same issue. I hope developers will take a look at this issue and will merge the PR.
